# Generated by Django 5.2 on 2026-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0004_alter_usuario_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='data_acesso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
