# Generated by Django 5.2 on 2026-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0005_alter_acesso_data_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='processamento_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
