# Generated by Django 5.2 on 2026-02-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0007_processamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='processamento_status',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='task_id',
        ),
    ]
