# Generated by Django 5.2 on 2026-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0008_remove_usuario_processamento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='task_id_parent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processamento',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
